In [2]:
import numpy as np


In [9]:
#create-from list
arr = np.array([1,2,3,4,5])
print(arr , type(arr))

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2 , type(arr2), arr2.dtype)

arr2D = np.array([[1,2,3] , [4,5,6] ,[7,8,9]])
print(arr2D , arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [22]:
#creating numpy arrays using built in arrays
arr1 = np.zeros((2,3)) #prefill
print(arr1 , arr1.shape)

arr2 = np.ones((2,3)) #prefil
print(arr2 , arr2.shape)

arr3 = np.full((3,4),100) #prefill with val
print(arr3 , arr3.shape)

arr4 = np.eye(3)
print(arr4 , arr4.shape)

arr5 = np.arange(1,10)
print(arr5 , arr5.shape)

arr6 = np.arange(1,11 , 2) #with skipping 2 elements
print(arr6 , arr6.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[1 2 3 4 5 6 7 8 9] (9,)
[1 3 5 7 9] (5,)


In [31]:
#Properties of arrays
arr = np.array([[1,2,3],[4,5,6] ,[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr , float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [43]:
#Operations on Array
arr = np.array([[1,2,3],[4,5,6]])
print(arr , arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped , reshaped.shape)

flattened = arr.flatten() #2D -> 1D
print(flattened , flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [3]:
#Indexing of Arrays

arr = np.array([1,2,3,4,5,6,4,3,8,12,43,22])
print(arr[0])
print(arr[1])
print(arr[2])

#Fancy indexing
idx= [0,2,4]
print(arr[idx]) #fancy indexing 

#Boolean indexing 
print(arr[arr > 4]) 

1
2
3
[1 3 5]
[ 5  6  8 12 43 22]


In [4]:
#Slicing 
arr =  np.array([1,3,2,5,4])
print(arr[1:4]) #start,end ,step]


[3 2 5]


In [5]:
#Copy vs View
nums = [1,2,3,4,5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)


[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [8]:
#DATA TYPES

arr = np.array([1,.12,2,4,5])
print(arr , arr.dtype)

#complex number 
cnum1 = np.array([3+4j])
cnum2 = np.array([2+4j])

print(cnum1+cnum2 , cnum1.dtype)

[1.   0.12 2.   4.   5.  ] float64
[5.+8.j] complex128
