In [4]:
#Multidimensional Array
import numpy as np

In [14]:
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D)

print(np.sum(arr2D))

sum_Columns = np.sum(arr2D , axis = 0) #for column
print(sum_Columns)

sum_of_rows = np.sum(arr2D , axis = 1) #for rows  
print(sum_of_rows)

print(arr2D[0:2 ,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


#### 3D Array
arr3D = np.array([[1,2], [3,4] , [5,6],[7,8],[9,10],[11 , 12]])
print(arr3D , arr3D.shape)

#indexing
print(arr3D[1,1,0])

#slicing
print(arr3D)

print(arr3D [i,0,:] )#first row from both layer
print(arr3D [i,0,:]) #first row from both layer
arr3D

      

In [31]:
# Vectorisation and BroadCasting

arr = np.array([1,2,3,4,5])
arr2 = np.array([1,6,7,8,5])


print(arr ** 2)
print(arr2 ** 2)
print(arr2 + arr)



[ 1  4  9 16 25]
[ 1 36 49 64 25]
[ 2  8 10 12 10]


In [33]:
#BroadCasting
arr = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,1]])

print(arr.shape)
print(arr2.shape)

print(arr+arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 7  9 11 13  6]]


In [36]:
#vector normalization
arr = np.array([[1,2],[3,4]])
mean = (np.mean(arr)) #mean
std_dev = (np.std(arr)) #stdard deviation

normalized_arr = (arr- mean) / std_dev;
print(normalized_arr)


[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [41]:
#Mathematical functions

#Aggregation

arr =np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))


15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [43]:
#log 
arr =np.array([1,2,3,4,5])

print(np.log(arr)) #log base e
print(np.log2(arr)) #log base 2

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         1.         1.5849625  2.         2.32192809]


In [50]:
#rounding

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

arr =np.array([1,2,3,4,5,5 , 3, 6])
print(np.unique(arr))

print(np.abs(arr))

3.0
4.0
3.0
3.0
[1 2 3 4 5 6]
[1 2 3 4 5 5 3 6]
