In [9]:
import torch
import torch.nn as nn;

In [10]:
# input = 
torch.manual_seed(42) # we can be very comp # its like setting random state
inputs= torch.tensor([1.0,2.0,3.0])
neuron  = nn.Linear(in_features=3, out_features=1)

In [11]:
output = neuron(inputs)

In [12]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [13]:
# verify formulas
neuron.weight @inputs + neuron.bias

tensor([1.5244], grad_fn=<AddBackward0>)

In [14]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)